# Generated by Django 3.1.7 on 2021-03-06 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chineseSpicyFlavor', '0002_auto_20210306_1527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='id',
            field=models.CharField(blank=True, default='755175', editable=False, max_length=6, primary_key=True, serialize=False, unique=True),
        ),
    ]
