# Generated by Django 3.1.7 on 2021-03-11 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chineseSpicyFlavor', '0003_auto_20210306_1529'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='orderQty',
        ),
        migrations.AlterField(
            model_name='order',
            name='id',
            field=models.CharField(blank=True, default='447681', editable=False, max_length=6, primary_key=True, serialize=False, unique=True),
        ),
    ]
