# Generated by Django 3.1.7 on 2021-03-26 04:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chineseSpicyFlavor', '0007_auto_20210324_1937'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='order',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='product',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='OrderItem',
        ),
    ]
