# Generated by Django 3.1.7 on 2021-04-05 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chineseSpicyFlavor', '0008_auto_20210325_2335'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='address',
        ),
        migrations.AddField(
            model_name='customer',
            name='email',
            field=models.EmailField(default='null', max_length=254),
        ),
        migrations.AddField(
            model_name='customer',
            name='name',
            field=models.CharField(default='null', max_length=20),
        ),
    ]
