# Generated by Django 3.1.7 on 2021-04-13 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guestorder',
            name='id',
            field=models.CharField(blank=True, default='119082', editable=False, max_length=6, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='id',
            field=models.CharField(blank=True, default='705153', editable=False, max_length=6, primary_key=True, serialize=False, unique=True),
        ),
    ]
