<<<<<<< HEAD:orders/migrations/0002_auto_20210429_1132.py
# Generated by Django 3.1.1 on 2021-04-29 16:32
=======
# Generated by Django 3.1.1 on 2021-04-29 19:26
>>>>>>> f2b383570297a3e099f1170460efc577d1a2ac0e:orders/migrations/0002_auto_20210429_1426.py

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='id',
<<<<<<< HEAD:orders/migrations/0002_auto_20210429_1132.py
            field=models.CharField(blank=True, default='638437', editable=False, max_length=6, primary_key=True, serialize=False, unique=True),
=======
            field=models.CharField(blank=True, default='770431', editable=False, max_length=6, primary_key=True, serialize=False, unique=True),
>>>>>>> f2b383570297a3e099f1170460efc577d1a2ac0e:orders/migrations/0002_auto_20210429_1426.py
        ),
    ]
