<<<<<<< HEAD:orders/migrations/0002_auto_20210429_1418.py
# Generated by Django 3.1.1 on 2021-04-29 19:18
=======
# Generated by Django 3.1.1 on 2021-04-30 19:32
>>>>>>> bf0558bff061570cab49495dc7f7d47f1742ab97:orders/migrations/0002_auto_20210430_1432.py

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='id',
<<<<<<< HEAD:orders/migrations/0002_auto_20210429_1418.py
            field=models.CharField(blank=True, default='480315', editable=False, max_length=6, primary_key=True, serialize=False, unique=True),
=======
            field=models.CharField(blank=True, default='110300', editable=False, max_length=6, primary_key=True, serialize=False, unique=True),
>>>>>>> bf0558bff061570cab49495dc7f7d47f1742ab97:orders/migrations/0002_auto_20210430_1432.py
        ),
    ]
