# Generated by Django 3.1.5 on 2021-04-03 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20210325_2354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='id',
            field=models.CharField(blank=True, default='324638', editable=False, max_length=6, primary_key=True, serialize=False, unique=True),
        ),
    ]
