# Generated by Django 3.1.1 on 2021-04-30 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20210430_1437'),
        ('orders', '0002_auto_20210430_1438'),
    ]

    operations = [
    ]
