# Generated by Django 3.1.7 on 2021-04-13 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20210413_1656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guestorder',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='order',
            name='id',
            field=models.CharField(blank=True, default='101506', editable=False, max_length=6, primary_key=True, serialize=False, unique=True),
        ),
    ]
