# Generated by Django 3.1.1 on 2021-04-29 00:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chineseSpicyFlavor', '0011_auto_20210407_1607'),
        ('orders', '0002_auto_20210428_1849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='address',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='chineseSpicyFlavor.address'),
        ),
        migrations.AlterField(
            model_name='order',
            name='id',
            field=models.CharField(blank=True, default='500973', editable=False, max_length=6, primary_key=True, serialize=False, unique=True),
        ),
    ]
