# Generated by Django 3.1.7 on 2021-04-23 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20210419_1329'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_pref',
            field=models.CharField(choices=[('DELIVERY', 'Delivery'), ('PICKUP', 'Pickup')], default='Pickup', max_length=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='id',
            field=models.CharField(blank=True, default='947538', editable=False, max_length=6, primary_key=True, serialize=False, unique=True),
        ),
    ]
