# Generated by Django 3.1.1 on 2021-05-05 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20210503_0002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='id',
            field=models.CharField(blank=True, default='885230', editable=False, max_length=6, primary_key=True, serialize=False, unique=True),
        ),
    ]
