# Generated by Django 3.1.1 on 2021-05-01 03:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chineseSpicyFlavor', '0011_auto_20210407_1607'),
        ('orders', '0003_merge_20210430_1505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chineseSpicyFlavor.address'),
        ),
        migrations.AlterField(
            model_name='order',
            name='id',
            field=models.CharField(blank=True, default='282377', editable=False, max_length=6, primary_key=True, serialize=False, unique=True),
        ),
    ]
