# Generated by Django 3.1.7 on 2021-04-03 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20210402_2304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='id',
            field=models.CharField(blank=True, default='752333', editable=False, max_length=6, primary_key=True, serialize=False, unique=True),
        ),
    ]
