# Generated by Django 3.1.5 on 2021-04-27 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20210425_2220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='id',
            field=models.CharField(blank=True, default='199674', editable=False, max_length=6, primary_key=True, serialize=False, unique=True),
        ),
    ]
