# Generated by Django 3.1.1 on 2021-04-29 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20210428_1904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='id',
            field=models.CharField(blank=True, default='173189', editable=False, max_length=6, primary_key=True, serialize=False, unique=True),
        ),
    ]
