# Generated by Django 3.1.7 on 2021-04-05 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_auto_20210403_1208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='id',
            field=models.CharField(blank=True, default='491762', editable=False, max_length=6, primary_key=True, serialize=False, unique=True),
        ),
    ]
