# Generated by Django 3.1.7 on 2021-04-05 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_auto_20210405_1505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='id',
            field=models.CharField(blank=True, default='376821', editable=False, max_length=6, primary_key=True, serialize=False, unique=True),
        ),
    ]
