# Generated by Django 3.1.5 on 2021-04-14 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_auto_20210413_2248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='id',
            field=models.CharField(blank=True, default='771250', editable=False, max_length=6, primary_key=True, serialize=False, unique=True),
        ),
    ]
