# Generated by Django 3.1.1 on 2021-05-01 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_auto_20210430_2300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='id',
            field=models.CharField(blank=True, default='584435', editable=False, max_length=6, primary_key=True, serialize=False, unique=True),
        ),
    ]
