# Generated by Django 3.1.7 on 2021-04-07 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_auto_20210407_1418'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='id',
            field=models.CharField(blank=True, default='882850', editable=False, max_length=6, primary_key=True, serialize=False, unique=True),
        ),
    ]
