# Generated by Django 3.1.5 on 2021-04-15 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_auto_20210414_0941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='id',
            field=models.CharField(blank=True, default='682615', editable=False, max_length=6, primary_key=True, serialize=False, unique=True),
        ),
    ]
