# Generated by Django 3.1.1 on 2021-05-02 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_merge_20210430_1458'),
        ('orders', '0008_auto_20210430_2302'),
    ]

    operations = [
    ]
