# Generated by Django 3.1.7 on 2021-04-21 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_auto_20210415_1834'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_pref',
            field=models.CharField(choices=[('DELIVERY', 'Delivery'), ('PICKUP', 'Pickup')], default='PICKUP', max_length=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='id',
            field=models.CharField(blank=True, default='187949', editable=False, max_length=6, primary_key=True, serialize=False, unique=True),
        ),
    ]
